name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3s
    - name: install Utest
      run: sudo apt install -y libcppunit-dev
    - name: make
      run: make
    - name: make test
      run: make test
