name: C/C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: install Utest
        run: sudo apt install -y libcppunit-dev
      - name: make
        working-directory: ./src
        run: make
      - name: make test
        working-directory: ./src
        run: make test
